///--------------------------------------------------------------------------------------
/// @file	mr_case.h
/// @brief	Test case base class.
///
/// @author		Michael Roop
/// @date		2010
/// @version	1.0
///
/// Copyright 2010 Michael Roop
///--------------------------------------------------------------------------------------
#if !defined(MR_TEST_CASE_H)
#define MR_TEST_CASE_H

#include "mr_string.h"
#include "mr_sstream.h"
#include "mr_char.h"
#include "mr_testInfoObject.h"


namespace mr_test
{


///--------------------------------------------------------------------------------------
///
///	@brief	Pure virtual base class for all test cases.
///
/// This class encapsulates performance logging of each stage of the test.  As well, it
/// tracks the state and holds test information generated by the derived tests.
///
/// The test case object can be querried by the logger derived objects to assemble the 
/// information required.
///
/// Test case objects are constructed with a unique id string which is used to identify
/// and retrieve the test.  It is also constructed with a description string.
///
/// When the test case is retrieved, the arguments can be fed to it by means of the init
/// method.
///
/// There are three stages to a test case, the setup, the test, and the cleanup.
///
///--------------------------------------------------------------------------------------
class testCase
{

public:

	/// @brief	Status indicator for the test case.
	typedef enum Status
	{
		ST_NONE,		///< No status. Default.
		ST_SUCCESS,		///< Test was successful.
		ST_FAIL_INIT,	///< Test failed when init was called.
		ST_FAIL_SETUP,	///< Test failed on setup.
		ST_FAIL_TEST,	///< Test failed.
		ST_FAIL_CLEANUP,///< Test failed on cleanup.
		ST_NOT_EXISTS,	///< Test with unique id does not exist.

		ST_FAIL_FIXTURE_SETUP,
		ST_FAIL_FIXTURE_TEARDOWN

	} TestCaseStatus;


	///////////////////////////////////////////////////////////////////
	//				Start New Stuff                                  //   
	///////////////////////////////////////////////////////////////////

public:

	void RunTest(const mr_utils::mr_string& name, const TestArguments& args );

	// probably private
	void ResetTest();

	void ResetFixture();


	bool HasTest(const mr_utils::mr_string& name);

	const std::vector<mr_utils::mr_string>& GetTestNames();

protected:

	/// @brief	Typdef of a class method pointer with no param and no return to clean up syntax. 
	typedef void (testCase::*  testCase_ptr) ( void );

private:
	testCase_ptr m_fixtureSetup;	// setup method for the entire fixture
	testCase_ptr m_fixtureTeardown;	// teardown method for the entire fixture
	testCase_ptr m_testSetup;		// setup method for each test
	testCase_ptr m_testTeardown;	// teardown method for each test

	/// @brief	Determines if a test has been called on the fixture yet
	bool m_isFixtureCalled;

	/// @brief	List of tests registered in the test fixture
	std::vector<mr_utils::mr_string> m_testNames;
	
protected:

	/// @brief	Register a setup method to be executed once for the entire fixture
	/// @param	setup The setup method
	void RegisterFixtureSetup(testCase_ptr setup);


	/// @brief	Register a teardown method to be executed once for the entire fixture
	/// @param	teardown The teardown method
	void RegisterFixtureTeardown(testCase_ptr teardown);
	

	/// @brief	Register a setup method to be executed for each test in the fixture
	/// @param	setup The setup method
	void RegisterTestSetup(testCase_ptr setup);


	/// @brief	Register a teardown method to be executed for each test in the fixture
	/// @param	teardown The teardown method
	void RegisterTestTeardown(testCase_ptr teardown);


private:

	/// @brief	Wrapper function to wrap performance logging for various methods.
	///
	/// @param	timeVal	A reference to hold the timing information.
	/// @param	funcPtr	A pointer to the function to time.
	///
	/// @return	true if the function timed is successful, otherwise false.
	void ExecStep(long long& timeVal, testCase_ptr funcPtr, TestCaseStatus failStatus);



	///////////////////////////////////////////////////////////////////
	//                END NEW STUFF                                  //
	///////////////////////////////////////////////////////////////////


public:

	/// @brief	Constructor
	///	@param	name	Name of the test case.
	///	@param	desc	Description of test case.
	testCase( const mr_utils::mr_string& name, const mr_utils::mr_string& desc );


	/// @brief	Initialise method for two phase construction.
	///			This is fed into the test case by the engine just before the setup is called.
	///	@param	args	Any args that you want to send to the test case.
	///
	///	@return	true if successful, otherwise false.
	virtual bool init( const TestArguments& args );


	/// @brief	Override to setup test before test is run in test method. Default 
	///			returns true.
	///
	/// @return	true if successful, otherwise false.
	virtual bool setup();


	/// @brief	Override to execute test code.
	///
	/// @return	true if successful, otherwise false.
	virtual bool test() = 0;


	/// @brief	Override to clean up after test is run. Default returns true.
	///
	/// @return	true if successful, otherwise false.
	virtual bool cleanup();


	/// @brief	Retrieve uniquely indentifying test name.
	///
	/// @return	The unique name of the test.
	const mr_utils::mr_string& name() const;


	/// @brief	Retrieve test description.
	///
	/// @return	The description of the test.
	const mr_utils::mr_string& desc() const;


	/// @brief	Retrieve test arguments.
	///
	/// @return	The arguments for the test.
	const TestArguments& args() const;


	/// @brief	Retrieve the test status in string format.
	///
	/// @exception	throws an mr_exception if the status is not accounted
	///				for.  This would be a programming error.
	/// @return	The status of the test.
	mr_utils::mr_string status() const;


	/// @brief	Retrieve the test status in enum format.
	///
	/// @return	The status of the test.
	TestCaseStatus statusEnum() const;


	/// @brief	Retrieve the performance timing for the test setup.
	///
	/// @return	The time in ms that the setup took.
	long long setupTime() const;


	/// @brief	Retrieve the performance timing for the test.
	///
	/// @return	The time in ms that the test took.
	long long execTime() const;


	/// @brief	Retrieve the performance timing for the test cleanuup.
	///
	/// @return	The time in ms that the cleanup took.
	long long cleanupTime() const;

	// Only used by the engine

	/// @brief	Called by the engine when the test is selected.
	///
	///	Allows the test to be created before the arguments for the test are known. In this
	/// way a test case code can be used in different ways depending on the arguments that
	/// are read in at select time.  Part of the arguments can also be expected return value.
	///
	/// The test is instantiated and stored.  When it is selected, the arguments are know from 
	/// the same script from which is was selected.
	///
	/// @param	args	A TestArguments object with the arguments for the test.
	bool executeInit(  const TestArguments& args );


	/// @brief	Executes and times the test setup. Only ever called by the testEngine.
	/// 
	/// @return true if successful, otherwise false.
	bool executeSetup();


	/// @brief	Executes and times the test itself. Only ever called by the testEngine.
	/// 
	/// @return true if successful, otherwise false.
	bool executeTest();


	/// @brief	Executes and times the test cleanup. Only ever called by the testEngine.
	/// 
	/// @return true if successful, otherwise false.
	bool executeCleanup();


	/// @brief	Retrieve the message buffer.
	///
	///	Call to add messages from your tests. You would usualy use this to document
	///	a failure condition. This is usually put out to the shorter summary logs.
	///
	/// @return	The test message buffer.
	mr_utils::mr_stringstream& getMsgBuffer();


	/// @brief	Retrieve the message buffer.
	///
	///	This contains the details of failures from the comparison macros. These are usually
	/// more detailed and are sent to a specific log.
	///
	/// @return	The test message buffer.
	mr_utils::mr_stringstream& getVerboseBuffer();

protected:
	TestCaseStatus				m_status;			///< Status of the test case.

private:

	mr_utils::mr_string			m_name;				///< Test name.
	mr_utils::mr_string			m_desc;				///< Test description.
	TestArguments				m_args;				///< Test arguments.

	mr_utils::mr_stringstream	m_buffer;			///< Short message buffer.
	mr_utils::mr_stringstream	m_verboseBuffer;	///< Verbose message buffer.
	long long					m_setupTime;		///< Setup time in ms.
	long long					m_execTime;			///< Test time in ms.
	long long					m_cleanupTime;		///< Cleanup time in ms.


	
	

	/// @brief	Protected default constructor to force use of regular constructor.
	testCase() ;


	/// @brief	Protected copy constructor to force use of regular constructor.
	///
	/// @param	tc	The testCase used for construction.
	testCase( const testCase& tc );


	/// @brief	Typdef of a class method pointer to clean up syntax. 
	typedef bool (testCase::*  step_ptr) ( void );


	/// @brief	Wrapper function to wrap performance logging for various methods.
	///
	/// @param	timeVal	A reference to hold the timing information.
	/// @param	funcPtr	A pointer to the function to time.
	///
	/// @return	true if the function timed is successful, otherwise false.
	bool execStep( long long& timeVal, step_ptr funcPtr );


	/// @brief	Helper method to set the status.
	///
	/// @param	isOk		The status of the current test.
	/// @param	failStatus	The status to set upon failure.
	///
	/// @return	The same status as the argument isOk.
	bool setStatus( bool isOk, TestCaseStatus failStatus );


};



} // end namespace.

#endif